import slugify from '../utils/slugify'

export default {
  title: "Project",
  name: 'project',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this project",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Project Code",
      description: "The project code for this project, eg: 'BH.01'",
      name: "projectCode",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Teaser Image",
      description: "The teaser image which will be shown on the projects index",
      name: "teaserImage",
      type: "defaultImage",
      validation: Rule => Rule.required()
    },
    {
      title: "Gallery Images",
      description: "The image gallery for this project",
      name: "galleryImages",
      type: 'array',
      of: [
        {type: 'defaultImage', title: 'Image'},
      ],
      options: {
        layout: 'grid',
      },
      validation: Rule => Rule.required()
    },
    {
      title: "Project Info",
      description: "The text that will appear in the 'Project Info' section",
      name: "projectInfo",
      type: 'array', 
      of: [{type: 'block'}],
      validation: Rule => Rule.required()
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'projectCode',
      media: 'teaserImage'
    }
  }
}